### ISSUE TITLE
zoopkeeper用户密码第二次修改后就进不了管理页面了

### ISSUE THREAD

**Issue by likaiyong** [nmyphp/tbschedule#20]

**Comment by nmyphp** [comment]
回到console登录页（http://localhost:8080/schedule/index.jsp?manager=true），重新输入正确密码即可

**Comment by likaiyong** [comment]
同时无法进入其他页面，可能由于采用不同的用户名密码配置过同一目录造zookeeper数据异常，可以在zookeeper中手动删除目录数据，或者更换新目录后重启应用。

在zookeeper中删除目录方法：

[root@192.168.1.5]$ ./zkClient.sh

[zk: localhost:2181(CONNECTED) 0] addauth digest admin:password

[zk: localhost:2181(CONNECTED) 1] rmr /app-schedule/demo
